channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - pytorch-lightning==1.6.1
  - ax-platform
  - torchvision>=0.9.1
  - torch>=1.9.0
  - protobuf<4.0.0
  # gyptorch 1.9.0 is incompatible with the versions of botorch
  # required by many versions of pytorch
  - gpytorch!=1.9.0
